import Head from 'next/head';
import Image from 'next/image';
import { Globe, GitHub, Linkedin, Instagram, Twitter } from 'react-feather';

export default function Home() {
  return (
    <>
      <Head>
        <title>Business Card | NextJS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex h-48 w-96 flex-col divide-y divide-slate-200 overflow-hidden rounded-lg bg-white shadow">
          <div className="flex grow p-2">
            <Image
              src={'/images/nick.png'}
              alt="Portrait of Nick Richardson"
              width={120}
              height={120}
              className="h-32 w-32 rounded-md"
            />
            <div className="h=32 flex flex-col content-start justify-center pl-3 text-base font-medium">
              <h3 className="text-lg font-bold">Nick Richardson</h3>
              <p>Senior UI Designer</p>
              <p>Sarasota, Florida</p>
            </div>
          </div>
          <div className="item flex h-16 justify-center p-2">
            <div className="flex w-48 items-center justify-between">
              <a href="https://nicjrich.dev/" target={'_blank'}>
                <Globe className="h-5 w-5" />
              </a>
              <a href="https://github.com/nicjrichDEV" target={'_blank'}>
                <GitHub className="h-5 w-5" />
              </a>
              <a
                href="https://www.linkedin.com/in/nicjrichdev/"
                target={'_blank'}
              >
                <Linkedin className="h-5 w-5" />
              </a>
              <a
                href="https://www.instagram.com/nicjrichdev/"
                target={'_blank'}
              >
                <Instagram className="h-5 w-5" />
              </a>
              <a href="https://twitter.com/nicjrichdev" target={'_blank'}>
                <Twitter className="h-5 w-5" />
              </a>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
